// <auto-generated />
using System;
using Api.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Infrastructure.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260522063733_AddOnboardingFields")]
    partial class AddOnboardingFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Features.Billing.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Api.Features.Notarization.ElectronicNotarialBookEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EnpId")
                        .HasColumnType("uuid");

                    b.Property<int>("EntryNumber")
                        .HasColumnType("integer");

                    b.Property<decimal>("FeeCharged")
                        .HasColumnType("numeric");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<string>("NotarialAct")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NotarizedFileId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PrincipalActualLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrincipalAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid");

                    b.Property<string>("PrincipalIdentityEvidence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PrincipalLocationType")
                        .HasColumnType("integer");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PrincipalId");

                    b.HasIndex("EnpId", "EntryNumber")
                        .IsUnique();

                    b.ToTable("NotarialBookEntries");
                });

            modelBuilder.Entity("Api.Features.Notarization.NotarizationDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EnpId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("NotarizationSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("PdfAFileId")
                        .HasColumnType("text");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EnpId");

                    b.HasIndex("NotarizationSessionId");

                    b.HasIndex("PrincipalId");

                    b.ToTable("NotarizationDocuments");
                });

            modelBuilder.Entity("Api.Features.Notarization.NotarizationSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EnpId")
                        .HasColumnType("uuid");

                    b.Property<string>("EnpLocation")
                        .HasColumnType("text");

                    b.Property<int>("EnpLocationType")
                        .HasColumnType("integer");

                    b.Property<bool>("GeolocationVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("MeetingUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid");

                    b.Property<string>("PrincipalLocation")
                        .HasColumnType("text");

                    b.Property<int>("PrincipalLocationType")
                        .HasColumnType("integer");

                    b.Property<string>("RecordingFileId")
                        .HasColumnType("text");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EnpId");

                    b.HasIndex("PrincipalId");

                    b.ToTable("NotarizationSessions");
                });

            modelBuilder.Entity("Api.Features.Notarization.NotarizationWitness", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("BookEntryId")
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("IdentityEvidence")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Signature")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BookEntryId");

                    b.HasIndex("SessionId");

                    b.ToTable("NotarizationWitnesses");
                });

            modelBuilder.Entity("Api.Features.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CommissionExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CommissionNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DigitalCertificate")
                        .HasColumnType("text");

                    b.Property<string>("EkycStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("none");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IbpNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsEnp")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnboarded")
                        .HasColumnType("boolean");

                    b.Property<string>("RegularPlaceOfBusiness")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RollNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("WatchedInstructionalVideo")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Api.Features.Billing.Subscription", b =>
                {
                    b.HasOne("Api.Features.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Features.Notarization.ElectronicNotarialBookEntry", b =>
                {
                    b.HasOne("Api.Features.Users.User", "Enp")
                        .WithMany()
                        .HasForeignKey("EnpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Features.Users.User", "Principal")
                        .WithMany()
                        .HasForeignKey("PrincipalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enp");

                    b.Navigation("Principal");
                });

            modelBuilder.Entity("Api.Features.Notarization.NotarizationDocument", b =>
                {
                    b.HasOne("Api.Features.Users.User", "Enp")
                        .WithMany()
                        .HasForeignKey("EnpId");

                    b.HasOne("Api.Features.Notarization.NotarizationSession", null)
                        .WithMany("Documents")
                        .HasForeignKey("NotarizationSessionId");

                    b.HasOne("Api.Features.Users.User", "Principal")
                        .WithMany()
                        .HasForeignKey("PrincipalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enp");

                    b.Navigation("Principal");
                });

            modelBuilder.Entity("Api.Features.Notarization.NotarizationSession", b =>
                {
                    b.HasOne("Api.Features.Users.User", "Enp")
                        .WithMany()
                        .HasForeignKey("EnpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Features.Users.User", "Principal")
                        .WithMany()
                        .HasForeignKey("PrincipalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enp");

                    b.Navigation("Principal");
                });

            modelBuilder.Entity("Api.Features.Notarization.NotarizationWitness", b =>
                {
                    b.HasOne("Api.Features.Notarization.ElectronicNotarialBookEntry", null)
                        .WithMany("Witnesses")
                        .HasForeignKey("BookEntryId");

                    b.HasOne("Api.Features.Notarization.NotarizationSession", null)
                        .WithMany("Witnesses")
                        .HasForeignKey("SessionId");
                });

            modelBuilder.Entity("Api.Features.Notarization.ElectronicNotarialBookEntry", b =>
                {
                    b.Navigation("Witnesses");
                });

            modelBuilder.Entity("Api.Features.Notarization.NotarizationSession", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Witnesses");
                });
#pragma warning restore 612, 618
        }
    }
}
